### ISSUE TITLE
CMake deprecation

### ISSUE THREAD

**Issue by joaander** [glotzerlab/libgetar#22]
When building HOOMD, CMake issues the following warning in the embedded libgetar (with cmake 3.19.0):
```
CMake Deprecation Warning at hoomd/extern/libgetar/CMakeLists.txt:2 (CMAKE_MINIMUM_REQUIRED):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.
```

Could we bump the minimum required cmake version in libgetar? Most packages are require some 3.x release in recent days. HOOMD now requires 3.9, and pybind11 requires 3.4.

**Comment by klarh** [comment]
This should be doable; I think I had previously set the minimum version based on the required features I was using in the cmake build scripts, rather than targeting any particular release date or OS version.
